[package]
name = "pyrust-py"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyrust_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.2"
pyrust-lib = { path = "../pyrust-lib" }
